# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
    - develop
pool:
  vmImage: 'windows-latest'


variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: 0
  minor: 97
  patchNo: $[counter(variables['minor'], 1)]
  buildNo: $[counter('versioncounter', 100)]
  suffix: $[replace(variables['Build.SourceBranchName'], '_', '-')]

name: $(BuildDefinitionName)_$(major).$(minor).$(buildNo).$(patchNo)-$(suffix)

jobs:
- job: Build
  steps:

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.100'
  - task: VersionDotNetCoreAssemblies@3
    displayName: 'Version files'
    inputs:
      Path: '$(Build.SourcesDirectory)'
      VersionNumber: '$(Build.BuildNumber)'
      Injectversion: False
      VersionRegex: '\d+\.\d+\.\d+\.\d+'
      FilenamePattern: 'directory.build.props'
      AddDefault: true
      OutputVersion: 'OutputedVersion'
  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      projects: '**/*.sln'
      feedsToUse: 'config'
      nugetConfigPath: 'nuget.config'

  - task: DotNetCoreCLI@2
    displayName: 'Build & Pack'
    inputs:
      command: 'pack'
      packagesToPack: '**/*.sln'
      versioningScheme: 'off'

  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: '**/*.Tests.csproj'
      #arguments: '-v normal -l "console;verbosity=detailed"'
  
  - task: CopyFiles@2
    name: ''
    displayName: 'Copy Nuget Packages to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: $(build.sourcesdirectory)
      Contents: '**\bin\$(BuildConfiguration)\**\*.nupkg'
      TargetFolder: $(build.artifactstagingdirectory)

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)

  - task: NuGetCommand@2
    displayName: 'Publish to FlexGet'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'f8484947-4741-4322-87d4-9a1586904e2d'

  